### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by j00hwan** [mspnp/architecture-center.ko-kr#3]
[성능 및 확장성]
..   "가용성"은 성능에 영향을 주지 않고 부하 증가를 처리하거나 ...  =&gt; "확장성"은 성능에 영향을 주지 않고 부하 증가를 처리하거나

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 0a4ecd26-cb7b-4cb2-ae3a-3748ada92771
* Version Independent ID: 97f96179-a22b-8401-a2f4-264a86b5d2f5
* Content: [클라우드 디자인 패턴](https://docs.microsoft.com/ko-kr/azure/architecture/patterns/)
* Content Source: [docs/patterns/index.md](https://github.com/mspnp/architecture-center.ko-kr/blob/live/docs/patterns/index.md)
* Service: **guidance**
* GitHub Login: @davidyoon
* Microsoft Alias: **pnp**

**Comment by LisandroSu** [comment]
안녕하세요 , @j00hwan 
피드백을 주셔서 감사합니다. 

사용자의 의견을 적극적으로 검토하고 있으며 곧 답변을 드리겠습니다. 

감사합니다. 
Microsoft DOCS 국제 팀

**Comment by LisandroSu** [comment]
안녕하세요, @j00hwan 님.  

피드백을 주셔서 감사합니다. 
 
당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/azure/architecture/patterns/ 에 게시했습니다.  

당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다. 

감사합니다. 
Microsoft DOCS 국제 팀
