### ISSUE TITLE
shared-nothing 아키텍처로 전환 번역

### ISSUE THREAD

**Issue by j00hwan** [mspnp/architecture-center.ko-kr#4]
예를 들어 서버 쪽 세션 상태, 클라이언트 선호도 및 데이터 분할을 사용하지 못하도록 하는 것은 비공유 아키텍처로 전환하는 좋은 예입니다 ==> 예를 들어 서버 쪽 세션 상태, 클라이언트 선호도를 사용하지 않으며 데이터 분할을 하는 것은 비공유 아키텍처로 전환하는 좋은 예입니다
For example, avoiding the use of server-side session state, client affinity, and data partitioning are good examples of moving towards a shared-nothing architecture.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: b79636ce-83ec-b5ba-fc6b-25c397516dd9
* Version Independent ID: 4f8cc5c2-4473-1ca8-b901-6329eb920e8c
* Content: [확장성 검사 목록](https://docs.microsoft.com/ko-kr/azure/architecture/checklist/scalability)
* Content Source: [docs/checklist/scalability.md](https://github.com/mspnp/architecture-center.ko-kr/blob/live/docs/checklist/scalability.md)
* Service: **guidance**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by LisandroSu** [comment]
안녕하세요, @j00hwan  

피드백을 주셔서 감사합니다. 

사용자의 의견을 적극적으로 검토하고 있으며 곧 답변을 드리겠습니다. 

감사합니다. 
Microsoft DOCS 국제 팀

**Comment by CeciAc** [comment]
안녕하세요, @j00hwan님. 
 언어 피드백을 주셔서 감사합니다.  
 귀하의 피드백을 검토한 결과, 당사 언어 팀은: 
 
 피드백 감사합니다. 제안해 주신 수정본("예를 들어 서버 쪽 세션 상태, 클라이언트 선호도를 사용하지 않으며 데이터 분할을 하는 것은 비공유 아키텍처로 전환하는 좋은 예입니다")에서는 소스의 3가지 use 여부가 각각 (1)와 (2)는 사용하지 않는 것으로 번역된 반면 (3)은 사용하는 것으로 번역이 되어, 소스에서 말하는 'avoiding the use of (1), (2) and (3)'이 정확히 반영되지 않은 것으로 보입니다.

--대신, 다음 수정 번역을 제안합니다.
"예를 들어 서버 쪽 세션 상태, 클라이언트 선호도 및 데이터 분할을 사용하지 않는 것은 비공유 아키텍처로 전환하는 좋은 예입니다."
 
 아쉽지만 수용 기준에 완전히 일치하지 않는다고 판단했습니다. 
 당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다.  

 감사합니다. 
Microsoft DOCS 국제 팀
