### ISSUE TITLE
야생 파사드?

### ISSUE THREAD

**Issue by klimtever** [mspnp/architecture-center.ko-kr#6]
[여기에 피드백 입력]
1. 그림에서 Strangler Facade 를 "야생 파사드"로 되어 있는데,
"야생"에 다른 의미가 없다면  "스트랭글러 파사드"로 표기하는게 적절하겠습니다. 

2. Facade를 "외관"으로 번역한다면, 그림에 사용된 "파사드"도 "외관"으로 통일하는게 좋겠습니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 5b580bcd-bba9-0799-6f9f-4b0e2ae9739f
* Version Independent ID: 6603e60e-ad3b-9aec-0633-eed88c218561
* Content: [스트랭글러 패턴](https://docs.microsoft.com/ko-kr/azure/architecture/patterns/strangler)
* Content Source: [docs/patterns/strangler.md](https://github.com/mspnp/architecture-center.ko-kr/blob/live/docs/patterns/strangler.md)
* Service: **guidance**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by LisandroSu** [comment]
안녕하세요. , @klimtever 

피드백을 주셔서 감사합니다. 
사용자의 의견을 적극적으로 검토하고 있으며 곧 답변을 드리겠습니다. 

감사합니다. 
Microsoft DOCS 국제 팀

**Comment by dragon119** [comment]
Hi,

I'm a PM in patterns & practices team.  I don't understand what it says but it's about our guidance on Azure Architecture Center, right? Let me know if you need any help from us.

Thanks,
Masashi


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by klimtever** [comment]
Hi,
If possible, can you please allow a Korean translator to review my feedback?

Thanks,
Kilimtever

**Comment by CeciAc** [comment]
Hi @klimtever 
Sorry for the delay, our linguists were overloaded this week, we already sent your feedback to our Korean reviewer and will be back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
안녕하세요, @klimtever
 피드백을 주셔서 감사합니다. 
 당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/azure/architecture/patterns/strangler에 게시했습니다.  
 당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다. 
 감사합니다. 
Microsoft DOCS 국제 팀
