### ISSUE TITLE
"Azure 기능"이라고 표시되어 있는 것은 Azure Function 으로 변경해주시면 좋겠습니다.

### ISSUE THREAD

**Issue by iz4blue** [mspnp/architecture-center.ko-kr#9]
한글로 번역된 내용을 읽다가 보니 "Azure 기능" 이라고 적혀 있는 부분이 참 어색합니다.
그리고 공식 명칭도 "Azure Fuctions" 인지? "Azure Function" 인지 조금 해깔리네요.
아무튼 공식 명칭으로 변경해주시면 더 좋을 것 같습니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 30d02f16-9621-d204-4132-8ce8db79b0af
* Version Independent ID: 65b4385b-79f0-d842-d4a1-5d013615f9b1
* Content: [Azure 및 AWS 서비스 비교 - 다중 클라우드](https://docs.microsoft.com/ko-kr/azure/architecture/aws-professional/services)
* Content Source: [docs/aws-professional/services.md](https://github.com/mspnp/architecture-center.ko-kr/blob/live/docs/aws-professional/services.md)
* Service: **guidance**
* GitHub Login: @lbrader
* Microsoft Alias: **pnp**

**Comment by CeciAc** [comment]
안녕하세요, @iz4blue 
 피드백을 주셔서 감사합니다. 
 당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/azure/architecture/aws-professional/services 에 게시했습니다.  
 당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다. 
 감사합니다. 
Microsoft DOCS 국제 팀
